from sqlmodel import Session, create_engine, select
from local_llama.models.cpu_type import CPUType
import os
from dotenv import load_dotenv

load_dotenv()

def seed_cputypes():
    """Seed the CPUType table with predefined CPU type data."""
    
    # Create database engine
    database_url = os.getenv("DATABASE_URL")
    if not database_url:
        raise ValueError("DATABASE_URL environment variable is not set")
    
    engine = create_engine(database_url)
    
    # CPUType data to insert
    cputypes_data = [
        {"cpu_name": "Intel 4004"},
        {"cpu_name": "Intel 8008"},
        {"cpu_name": "Intel 8080"},
        {"cpu_name": "Intel 8085"},
        {"cpu_name": "Intel 8086"},
        {"cpu_name": "Intel 8088"},
        {"cpu_name": "Intel 80186"},
        {"cpu_name": "Intel 80188"},
        {"cpu_name": "Intel 80286"},
        {"cpu_name": "Intel 80386SX"},
        {"cpu_name": "Intel 80386DX"},
        {"cpu_name": "Intel 80486SX"},
        {"cpu_name": "Intel 80486DX"},
        {"cpu_name": "Intel 80486DX2"},
        {"cpu_name": "Intel 80486DX4"},
        {"cpu_name": "Intel Pentium"},
        {"cpu_name": "Intel Pentium MMX"},
        {"cpu_name": "Intel Pentium Pro"},
        {"cpu_name": "Intel Pentium II"},
        {"cpu_name": "Intel Pentium III"},
        {"cpu_name": "Intel Pentium 4"},
        {"cpu_name": "Intel Pentium 4 Extreme Edition"},
        {"cpu_name": "Intel Pentium D"},
        {"cpu_name": "Intel Pentium M"},
        {"cpu_name": "Intel Core Duo"},
        {"cpu_name": "Intel Core Solo"},
        {"cpu_name": "Intel Core 2 Duo"},
        {"cpu_name": "Intel Core 2 Quad"},
        {"cpu_name": "Intel Core 2 Extreme"},
        {"cpu_name": "Intel Core i3"},
        {"cpu_name": "Intel Core i5"},
        {"cpu_name": "Intel Core i7"},
        {"cpu_name": "Intel Core i9"},
        {"cpu_name": "Intel Core Ultra 5"},
        {"cpu_name": "Intel Core Ultra 7"},
        {"cpu_name": "Intel Core Ultra 9"},
        {"cpu_name": "Intel Celeron"},
        {"cpu_name": "Intel Celeron M"},
        {"cpu_name": "Intel Pentium Silver"},
        {"cpu_name": "Intel Pentium Gold"},
        {"cpu_name": "Intel Xeon E3-1200"},
        {"cpu_name": "Intel Xeon E5-2600"},
        {"cpu_name": "Intel Xeon E5-4600"},
        {"cpu_name": "Intel Xeon E7-8800"},
        {"cpu_name": "Intel Xeon Scalable Platinum"},
        {"cpu_name": "Intel Xeon Scalable Gold"},
        {"cpu_name": "Intel Xeon Scalable Silver"},
        {"cpu_name": "Intel Xeon Scalable Bronze"},
        {"cpu_name": "Intel Xeon Phi"},
        {"cpu_name": "Intel Xeon D"},
        {"cpu_name": "Intel Xeon W"},
        {"cpu_name": "Intel Atom Z"},
        {"cpu_name": "Intel Atom N"},
        {"cpu_name": "Intel Atom E"},
        {"cpu_name": "Intel Atom C"},
        {"cpu_name": "Intel Atom S"},
        {"cpu_name": "Intel Itanium"},
        {"cpu_name": "Intel Itanium 2"},
        {"cpu_name": "Intel Quark"},
        {"cpu_name": "Intel 8051"},
        {"cpu_name": "AMD Am286"},
        {"cpu_name": "AMD Am386SX"},
        {"cpu_name": "AMD Am386DX"},
        {"cpu_name": "AMD Am486SX"},
        {"cpu_name": "AMD Am486DX"},
        {"cpu_name": "AMD K5"},
        {"cpu_name": "AMD K6"},
        {"cpu_name": "AMD K6-2"},
        {"cpu_name": "AMD K6-III"},
        {"cpu_name": "AMD Athlon"},
        {"cpu_name": "AMD Athlon XP"},
        {"cpu_name": "AMD Athlon 64"},
        {"cpu_name": "AMD Athlon 64 X2"},
        {"cpu_name": "AMD Duron"},
        {"cpu_name": "AMD Sempron"},
        {"cpu_name": "AMD Opteron 200"},
        {"cpu_name": "AMD Opteron 800"},
        {"cpu_name": "AMD Opteron 6200"},
        {"cpu_name": "AMD Opteron 6300"},
        {"cpu_name": "AMD Phenom"},
        {"cpu_name": "AMD Phenom II"},
        {"cpu_name": "AMD FX-4100"},
        {"cpu_name": "AMD FX-6100"},
        {"cpu_name": "AMD FX-8100"},
        {"cpu_name": "AMD FX-8300"},
        {"cpu_name": "AMD FX-8350"},
        {"cpu_name": "AMD Ryzen 3 1200"},
        {"cpu_name": "AMD Ryzen 3 1300X"},
        {"cpu_name": "AMD Ryzen 3 2200G"},
        {"cpu_name": "AMD Ryzen 3 3200G"},
        {"cpu_name": "AMD Ryzen 3 3100"},
        {"cpu_name": "AMD Ryzen 3 3300X"},
        {"cpu_name": "AMD Ryzen 3 4300G"},
        {"cpu_name": "AMD Ryzen 3 5300G"},
        {"cpu_name": "AMD Ryzen 3 4100"},
        {"cpu_name": "AMD Ryzen 3 4300U"},
        {"cpu_name": "AMD Ryzen 3 5300U"},
        {"cpu_name": "AMD Ryzen 3 7320U"},
        {"cpu_name": "AMD Ryzen 3 8300"},
        {"cpu_name": "AMD Ryzen 5 1400"},
        {"cpu_name": "AMD Ryzen 5 1500X"},
        {"cpu_name": "AMD Ryzen 5 1600"},
        {"cpu_name": "AMD Ryzen 5 1600X"},
        {"cpu_name": "AMD Ryzen 5 2400G"},
        {"cpu_name": "AMD Ryzen 5 2600"},
        {"cpu_name": "AMD Ryzen 5 2600X"},
        {"cpu_name": "AMD Ryzen 5 3400G"},
        {"cpu_name": "AMD Ryzen 5 3600"},
        {"cpu_name": "AMD Ryzen 5 3600X"},
        {"cpu_name": "AMD Ryzen 5 4600G"},
        {"cpu_name": "AMD Ryzen 5 5600G"},
        {"cpu_name": "AMD Ryzen 5 5600X"},
        {"cpu_name": "AMD Ryzen 5 7600"},
        {"cpu_name": "AMD Ryzen 5 7600X"},
        {"cpu_name": "AMD Ryzen 5 8600G"},
        {"cpu_name": "AMD Ryzen 7 1700"},
        {"cpu_name": "AMD Ryzen 7 1700X"},
        {"cpu_name": "AMD Ryzen 7 1800X"},
        {"cpu_name": "AMD Ryzen 7 2700"},
        {"cpu_name": "AMD Ryzen 7 2700X"},
        {"cpu_name": "AMD Ryzen 7 3700X"},
        {"cpu_name": "AMD Ryzen 7 3800X"},
        {"cpu_name": "AMD Ryzen 7 4700G"},
        {"cpu_name": "AMD Ryzen 7 5700G"},
        {"cpu_name": "AMD Ryzen 7 5800X"},
        {"cpu_name": "AMD Ryzen 7 7700"},
        {"cpu_name": "AMD Ryzen 7 7700X"},
        {"cpu_name": "AMD Ryzen 7 8700G"},
        {"cpu_name": "AMD Ryzen 9 3900X"},
        {"cpu_name": "AMD Ryzen 9 3950X"},
        {"cpu_name": "AMD Ryzen 9 5900X"},
        {"cpu_name": "AMD Ryzen 9 5950X"},
        {"cpu_name": "AMD Ryzen 9 7900"},
        {"cpu_name": "AMD Ryzen 9 7900X"},
        {"cpu_name": "AMD Ryzen 9 7950X"},
        {"cpu_name": "AMD Threadripper 1920X"},
        {"cpu_name": "AMD Threadripper 1950X"},
        {"cpu_name": "AMD Threadripper 2950X"},
        {"cpu_name": "AMD Threadripper 2970WX"},
        {"cpu_name": "AMD Threadripper 2990WX"},
        {"cpu_name": "AMD Threadripper 3960X"},
        {"cpu_name": "AMD Threadripper 3970X"},
        {"cpu_name": "AMD Threadripper 3990X"},
        {"cpu_name": "AMD Threadripper PRO 3945WX"},
        {"cpu_name": "AMD Threadripper PRO 3955WX"},
        {"cpu_name": "AMD Threadripper PRO 3975WX"},
        {"cpu_name": "AMD Threadripper PRO 3995WX"},
        {"cpu_name": "AMD Threadripper PRO 5945WX"},
        {"cpu_name": "AMD Threadripper PRO 5955WX"},
        {"cpu_name": "AMD Threadripper PRO 5965WX"},
        {"cpu_name": "AMD Threadripper PRO 5975WX"},
        {"cpu_name": "AMD Threadripper PRO 5995WX"},
        {"cpu_name": "AMD EPYC 7001 Naples"},
        {"cpu_name": "AMD EPYC 7002 Rome"},
        {"cpu_name": "AMD EPYC 7003 Milan"},
        {"cpu_name": "AMD EPYC 9004 Genoa"},
        {"cpu_name": "AMD EPYC 8004 Siena"},
        {"cpu_name": "AMD APU A4-Series"},
        {"cpu_name": "AMD APU A6-Series"},
        {"cpu_name": "AMD APU A8-Series"},
        {"cpu_name": "AMD APU A10-Series"},
        {"cpu_name": "AMD APU E-Series"},
        {"cpu_name": "AMD APU G-Series"},
        {"cpu_name": "AMD Athlon Neo"},
        {"cpu_name": "AMD Turion"},
        {"cpu_name": "AMD Geode"},
        {"cpu_name": "ARM Cortex-A5"},
        {"cpu_name": "ARM Cortex-A7"},
        {"cpu_name": "ARM Cortex-A8"},
        {"cpu_name": "ARM Cortex-A9"},
        {"cpu_name": "ARM Cortex-A12"},
        {"cpu_name": "ARM Cortex-A15"},
        {"cpu_name": "ARM Cortex-A17"},
        {"cpu_name": "ARM Cortex-A32"},
        {"cpu_name": "ARM Cortex-A35"},
        {"cpu_name": "ARM Cortex-A53"},
        {"cpu_name": "ARM Cortex-A55"},
        {"cpu_name": "ARM Cortex-A57"},
        {"cpu_name": "ARM Cortex-A65"},
        {"cpu_name": "ARM Cortex-A72"},
        {"cpu_name": "ARM Cortex-A73"},
        {"cpu_name": "ARM Cortex-A75"},
        {"cpu_name": "ARM Cortex-A76"},
        {"cpu_name": "ARM Cortex-A77"},
        {"cpu_name": "ARM Cortex-A78"},
        {"cpu_name": "ARM Cortex-A510"},
        {"cpu_name": "ARM Cortex-A520"},
        {"cpu_name": "ARM Cortex-A710"},
        {"cpu_name": "ARM Cortex-A715"},
        {"cpu_name": "ARM Cortex-X1"},
        {"cpu_name": "ARM Cortex-X2"},
        {"cpu_name": "ARM Cortex-X3"},
        {"cpu_name": "ARM Cortex-X4"},
        {"cpu_name": "ARM Cortex-M0"},
        {"cpu_name": "ARM Cortex-M0+"},
        {"cpu_name": "ARM Cortex-M3"},
        {"cpu_name": "ARM Cortex-M4"},
        {"cpu_name": "ARM Cortex-M7"},
        {"cpu_name": "ARM Cortex-M23"},
        {"cpu_name": "ARM Cortex-M33"},
        {"cpu_name": "ARM Cortex-M55"},
        {"cpu_name": "ARM Cortex-R4"},
        {"cpu_name": "ARM Cortex-R5"},
        {"cpu_name": "ARM Cortex-R7"},
        {"cpu_name": "ARM Cortex-R52"},
        {"cpu_name": "ARM Cortex-R82"},
        {"cpu_name": "ARM Neoverse N1"},
        {"cpu_name": "ARM Neoverse N2"},
        {"cpu_name": "ARM Neoverse V1"},
        {"cpu_name": "ARM Neoverse V2"},
        {"cpu_name": "Apple A4"},
        {"cpu_name": "Apple A5"},
        {"cpu_name": "Apple A5X"},
        {"cpu_name": "Apple A6"},
        {"cpu_name": "Apple A6X"},
        {"cpu_name": "Apple A7"},
        {"cpu_name": "Apple A8"},
        {"cpu_name": "Apple A8X"},
        {"cpu_name": "Apple A9"},
        {"cpu_name": "Apple A9X"},
        {"cpu_name": "Apple A10 Fusion"},
        {"cpu_name": "Apple A10X Fusion"},
        {"cpu_name": "Apple A11 Bionic"},
        {"cpu_name": "Apple A12 Bionic"},
        {"cpu_name": "Apple A12X Bionic"},
        {"cpu_name": "Apple A13 Bionic"},
        {"cpu_name": "Apple A14 Bionic"},
        {"cpu_name": "Apple A15 Bionic"},
        {"cpu_name": "Apple A16 Bionic"},
        {"cpu_name": "Apple A17 Pro"},
        {"cpu_name": "Apple A18"},
        {"cpu_name": "Apple A18 Pro"},
        {"cpu_name": "Apple M1"},
        {"cpu_name": "Apple M1 Pro"},
        {"cpu_name": "Apple M1 Max"},
        {"cpu_name": "Apple M1 Ultra"},
        {"cpu_name": "Apple M2"},
        {"cpu_name": "Apple M2 Pro"},
        {"cpu_name": "Apple M2 Max"},
        {"cpu_name": "Apple M2 Ultra"},
        {"cpu_name": "Apple M3"},
        {"cpu_name": "Apple M3 Pro"},
        {"cpu_name": "Apple M3 Max"},
        {"cpu_name": "Apple M4"},
        {"cpu_name": "Qualcomm Snapdragon 400"},
        {"cpu_name": "Qualcomm Snapdragon 410"},
        {"cpu_name": "Qualcomm Snapdragon 600"},
        {"cpu_name": "Qualcomm Snapdragon 615"},
        {"cpu_name": "Qualcomm Snapdragon 625"},
        {"cpu_name": "Qualcomm Snapdragon 650"},
        {"cpu_name": "Qualcomm Snapdragon 800"},
        {"cpu_name": "Qualcomm Snapdragon 801"},
        {"cpu_name": "Qualcomm Snapdragon 805"},
        {"cpu_name": "Qualcomm Snapdragon 808"},
        {"cpu_name": "Qualcomm Snapdragon 810"},
        {"cpu_name": "Qualcomm Snapdragon 820"},
        {"cpu_name": "Qualcomm Snapdragon 835"},
        {"cpu_name": "Qualcomm Snapdragon 845"},
        {"cpu_name": "Qualcomm Snapdragon 855"},
        {"cpu_name": "Qualcomm Snapdragon 865"},
        {"cpu_name": "Qualcomm Snapdragon 870"},
        {"cpu_name": "Qualcomm Snapdragon 888"},
        {"cpu_name": "Qualcomm Snapdragon 7 Gen 1"},
        {"cpu_name": "Qualcomm Snapdragon 7 Gen 3"},
        {"cpu_name": "Qualcomm Snapdragon 8 Gen 1"},
        {"cpu_name": "Qualcomm Snapdragon 8 Gen 2"},
        {"cpu_name": "Qualcomm Snapdragon 8 Gen 3"},
        {"cpu_name": "Qualcomm Krait 200"},
        {"cpu_name": "Qualcomm Krait 300"},
        {"cpu_name": "Qualcomm Krait 400"},
        {"cpu_name": "Qualcomm Kryo"},
        {"cpu_name": "Qualcomm Scorpion"},
        {"cpu_name": "Samsung Exynos 3 Single"},
        {"cpu_name": "Samsung Exynos 4 Dual"},
        {"cpu_name": "Samsung Exynos 4 Quad"},
        {"cpu_name": "Samsung Exynos 5 Dual"},
        {"cpu_name": "Samsung Exynos 5 Octa"},
        {"cpu_name": "Samsung Exynos 7 Octa"},
        {"cpu_name": "Samsung Exynos 8 Octa"},
        {"cpu_name": "Samsung Exynos 9 Octa"},
        {"cpu_name": "Samsung Exynos 9810"},
        {"cpu_name": "Samsung Exynos 990"},
        {"cpu_name": "Samsung Exynos 2100"},
        {"cpu_name": "Samsung Exynos 2200"},
        {"cpu_name": "MediaTek MT6580"},
        {"cpu_name": "MediaTek MT6735"},
        {"cpu_name": "MediaTek MT6750"},
        {"cpu_name": "MediaTek MT6771"},
        {"cpu_name": "MediaTek Helio P60"},
        {"cpu_name": "MediaTek Helio P70"},
        {"cpu_name": "MediaTek Helio X20"},
        {"cpu_name": "MediaTek Helio X30"},
        {"cpu_name": "MediaTek Dimensity 700"},
        {"cpu_name": "MediaTek Dimensity 800"},
        {"cpu_name": "MediaTek Dimensity 900"},
        {"cpu_name": "MediaTek Dimensity 1000"},
        {"cpu_name": "MediaTek Dimensity 2000"},
        {"cpu_name": "MediaTek Dimensity 7200"},
        {"cpu_name": "MediaTek Dimensity 8020"},
        {"cpu_name": "MediaTek Dimensity 9000"},
        {"cpu_name": "HiSilicon Kirin 900"},
        {"cpu_name": "HiSilicon Kirin 910"},
        {"cpu_name": "HiSilicon Kirin 920"},
        {"cpu_name": "HiSilicon Kirin 950"},
        {"cpu_name": "HiSilicon Kirin 960"},
        {"cpu_name": "HiSilicon Kirin 970"},
        {"cpu_name": "HiSilicon Kirin 980"},
        {"cpu_name": "HiSilicon Kirin 990"},
        {"cpu_name": "HiSilicon Kirin 9000"},
        {"cpu_name": "HiSilicon Kirin 9000S"},
        {"cpu_name": "Motorola 6800"},
        {"cpu_name": "Motorola 6809"},
        {"cpu_name": "Motorola 68000"},
        {"cpu_name": "Motorola 68010"},
        {"cpu_name": "Motorola 68020"},
        {"cpu_name": "Motorola 68030"},
        {"cpu_name": "Motorola 68040"},
        {"cpu_name": "Motorola 68060"},
        {"cpu_name": "Motorola PowerPC 601"},
        {"cpu_name": "Motorola PowerPC 603"},
        {"cpu_name": "Motorola PowerPC 604"},
        {"cpu_name": "IBM POWER1"},
        {"cpu_name": "IBM POWER2"},
        {"cpu_name": "IBM POWER3"},
        {"cpu_name": "IBM POWER4"},
        {"cpu_name": "IBM POWER5"},
        {"cpu_name": "IBM POWER6"},
        {"cpu_name": "IBM POWER7"},
        {"cpu_name": "IBM POWER8"},
        {"cpu_name": "IBM POWER9"},
        {"cpu_name": "IBM POWER10"},
        {"cpu_name": "IBM PowerPC 620"},
        {"cpu_name": "IBM PowerPC 750"},
        {"cpu_name": "IBM PowerPC G3"},
        {"cpu_name": "IBM PowerPC G4"},
        {"cpu_name": "IBM PowerPC G5"},
        {"cpu_name": "IBM Cell Broadband Engine"},
        {"cpu_name": "IBM z10"},
        {"cpu_name": "IBM z12"},
        {"cpu_name": "IBM z13"},
        {"cpu_name": "IBM z14"},
        {"cpu_name": "IBM z15"},
        {"cpu_name": "IBM z16"},
        {"cpu_name": "MIPS R2000"},
        {"cpu_name": "MIPS R3000"},
        {"cpu_name": "MIPS R4000"},
        {"cpu_name": "MIPS R4400"},
        {"cpu_name": "MIPS R4600"},
        {"cpu_name": "MIPS R5000"},
        {"cpu_name": "MIPS R8000"},
        {"cpu_name": "MIPS R10000"},
        {"cpu_name": "MIPS R12000"},
        {"cpu_name": "MIPS R14000"},
        {"cpu_name": "MIPS R16000"},
        {"cpu_name": "MIPS R5900"},
        {"cpu_name": "Sun SPARC"},
        {"cpu_name": "Sun UltraSPARC"},
        {"cpu_name": "Sun UltraSPARC II"},
        {"cpu_name": "Sun UltraSPARC III"},
        {"cpu_name": "Sun UltraSPARC IV"},
        {"cpu_name": "Sun UltraSPARC T1"},
        {"cpu_name": "Sun UltraSPARC T2"},
        {"cpu_name": "Sun SPARC T3"},
        {"cpu_name": "Sun SPARC T4"},
        {"cpu_name": "Sun SPARC T5"},
        {"cpu_name": "Sun SPARC M7"},
        {"cpu_name": "Sun SPARC M8"},
        {"cpu_name": "Sun Niagara"},
        {"cpu_name": "Oracle SPARC T8"},
        {"cpu_name": "HP PA-RISC 1.0"},
        {"cpu_name": "HP PA-RISC 1.1"},
        {"cpu_name": "HP PA-RISC 2.0"},
        {"cpu_name": "DEC Alpha 21064"},
        {"cpu_name": "DEC Alpha 21164"},
        {"cpu_name": "DEC Alpha 21264"},
        {"cpu_name": "DEC Alpha 21364"},
        {"cpu_name": "Hitachi SuperH SH-1"},
        {"cpu_name": "Hitachi SuperH SH-2"},
        {"cpu_name": "Hitachi SuperH SH-3"},
        {"cpu_name": "Hitachi SuperH SH-4"},
        {"cpu_name": "Renesas SH-4A"},
        {"cpu_name": "SiFive U54"},
        {"cpu_name": "SiFive U74"},
        {"cpu_name": "SiFive P270"},
        {"cpu_name": "SiFive P550"},
        {"cpu_name": "SiFive E31"},
        {"cpu_name": "SiFive E51"},
        {"cpu_name": "RISC-V RV32I"},
        {"cpu_name": "RISC-V RV32E"},
        {"cpu_name": "RISC-V RV64I"},
        {"cpu_name": "RISC-V RV64E"},
        {"cpu_name": "Cavium ThunderX"},
        {"cpu_name": "Cavium ThunderX2"},
        {"cpu_name": "Marvell ARMADA 7040"},
        {"cpu_name": "Marvell ARMADA 8040"},
        {"cpu_name": "Texas Instruments TMS320"},
        {"cpu_name": "Texas Instruments AM335x"},
        {"cpu_name": "Texas Instruments AM57x"},
        {"cpu_name": "Texas Instruments AM62x"},
        {"cpu_name": "Texas Instruments C6000"},
        {"cpu_name": "Texas Instruments Sitara AM3358"},
        {"cpu_name": "NXP i.MX6"},
        {"cpu_name": "NXP i.MX7"},
        {"cpu_name": "NXP i.MX8"},
        {"cpu_name": "NXP i.MX8M"},
        {"cpu_name": "NXP i.MX RT"},
        {"cpu_name": "NXP S32K"},
        {"cpu_name": "Broadcom BCM2835"},
        {"cpu_name": "Broadcom BCM2836"},
        {"cpu_name": "Broadcom BCM2837"},
        {"cpu_name": "Broadcom BCM2711"},
        {"cpu_name": "Rockchip RK3066"},
        {"cpu_name": "Rockchip RK3188"},
        {"cpu_name": "Rockchip RK3288"},
        {"cpu_name": "Rockchip RK3399"},
        {"cpu_name": "Rockchip RK3568"},
        {"cpu_name": "Rockchip RK3588"},
        {"cpu_name": "Allwinner A10"},
        {"cpu_name": "Allwinner A20"},
        {"cpu_name": "Allwinner A64"},
        {"cpu_name": "Allwinner H6"},
        {"cpu_name": "Allwinner H616"},
        {"cpu_name": "Allwinner H700"},
        {"cpu_name": "STM32F0"},
        {"cpu_name": "STM32F1"},
        {"cpu_name": "STM32F2"},
        {"cpu_name": "STM32F3"},
        {"cpu_name": "STM32F4"},
        {"cpu_name": "STM32F7"},
        {"cpu_name": "STM32H7"},
        {"cpu_name": "STM32MP157"},
        {"cpu_name": "NVIDIA Tegra 2"},
        {"cpu_name": "NVIDIA Tegra 3"},
        {"cpu_name": "NVIDIA Tegra K1"},
        {"cpu_name": "NVIDIA Tegra X1"},
        {"cpu_name": "NVIDIA Tegra X2"},
        {"cpu_name": "NVIDIA Orin"},
        {"cpu_name": "Zilog Z80"},
        {"cpu_name": "Zilog Z180"},
        {"cpu_name": "MOS 6502"},
        {"cpu_name": "MOS 6510"},
        {"cpu_name": "MOS 6581"},
        {"cpu_name": "Microchip PIC10"},
        {"cpu_name": "Microchip PIC12"},
        {"cpu_name": "Microchip PIC16"},
        {"cpu_name": "Microchip PIC18"},
        {"cpu_name": "Microchip PIC24"},
        {"cpu_name": "Microchip PIC32"},
        {"cpu_name": "Atmel AVR ATtiny"},
        {"cpu_name": "Atmel AVR ATmega"},
        {"cpu_name": "Atmel AVR ATxmega"},
        {"cpu_name": "Altera Nios II"},
        {"cpu_name": "Xilinx MicroBlaze"},
        {"cpu_name": "Synopsys ARC 600"},
        {"cpu_name": "Synopsys ARC 700"},
        {"cpu_name": "Tensilica Xtensa LX6"},
        {"cpu_name": "Tensilica Xtensa LX7"},
        {"cpu_name": "DEC VAX-11/780"},
        {"cpu_name": "Renesas RX62N"},
        {"cpu_name": "Renesas RX63N"},
        {"cpu_name": "Renesas RX64M"},
        {"cpu_name": "Elbrus E2K"},
        {"cpu_name": "Loongson LoongArch 3A5000"},
        {"cpu_name": "Loongson LoongArch 3C5000"},
        {"cpu_name": "OpenRISC 1000"},
        {"cpu_name": "OpenRISC 1200"},
        {"cpu_name": "Freescale 68HC05"},
        {"cpu_name": "Freescale 68HC08"},
        {"cpu_name": "Freescale 68HC11"},
        {"cpu_name": "Freescale ColdFire"},
        {"cpu_name": "Infineon TriCore"},
        {"cpu_name": "Infineon XMC4000"},
        {"cpu_name": "Analog Devices Blackfin"},
        {"cpu_name": "Analog Devices SHARC"},
        {"cpu_name": "Cypress PSoC 4"},
        {"cpu_name": "Cypress PSoC 5"},
        {"cpu_name": "Cypress PSoC 6"},
        {"cpu_name": "ESP8266"},
        {"cpu_name": "ESP32"},
        {"cpu_name": "ESP32-S2"},
        {"cpu_name": "ESP32-S3"},
        {"cpu_name": "ESP32-C3"},
        {"cpu_name": "MC6800"},
        {"cpu_name": "MC6809"},
        {"cpu_name": "WDC 65C02"},
        {"cpu_name": "WDC 65C816"},
        {"cpu_name": "Inmos T414"},
        {"cpu_name": "Inmos T800"},
        {"cpu_name": "NEC V20"},
        {"cpu_name": "NEC V30"},
        {"cpu_name": "Transmeta Crusoe"},
        {"cpu_name": "Transmeta Efficeon"},
        {"cpu_name": "VIA C3"},
        {"cpu_name": "VIA C7"},
        {"cpu_name": "VIA Nano"},
        {"cpu_name": "Ambiq Apollo"},
        {"cpu_name": "Atari 6502"},
        {"cpu_name": "Fujitsu FR-V"},
    ]
    
    with Session(engine) as session:
        # Check if CPU types already exist to avoid duplicates
        existing_cputypes = session.exec(select(CPUType)).all()
        existing_cpu_names = {cpu.cpu_name for cpu in existing_cputypes}
        
        cputypes_to_add = []
        for cpu_data in cputypes_data:
            if cpu_data["cpu_name"] not in existing_cpu_names:
                cputypes_to_add.append(CPUType(**cpu_data))
        
        if cputypes_to_add:
            session.add_all(cputypes_to_add)
            session.commit()
            print(f"Added {len(cputypes_to_add)} CPU types to the database.")
        else:
            print("All CPU types already exist in the database.")

if __name__ == "__main__":
    seed_cputypes()