from sqlmodel import Session, create_engine, select
from local_llama.models.gpu_type import GPUType
import os
from dotenv import load_dotenv

load_dotenv()

def seed_gputypes():
    """Seed the GPUType table with predefined GPU type data."""
    
    # Create database engine
    database_url = os.getenv("DATABASE_URL")
    if not database_url:
        raise ValueError("DATABASE_URL environment variable is not set")
    
    engine = create_engine(database_url)
    
    # GPUType data to insert
    gputypes_data = [
        {"gpu_name": "NEC uPD7220"},
        {"gpu_name": "Intel 82720"},
        {"gpu_name": "3Dlabs GLINT 300SX"},
        {"gpu_name": "3Dlabs Permedia"},
        {"gpu_name": "3Dlabs Permedia 2"},
        {"gpu_name": "Mitsubishi 3Dpro/2MP"},
        {"gpu_name": "Sony GPU PlayStation"},
        {"gpu_name": "NVIDIA NV1"},
        {"gpu_name": "NVIDIA RIVA 128"},
        {"gpu_name": "NVIDIA RIVA TNT"},
        {"gpu_name": "NVIDIA RIVA TNT2"},
        {"gpu_name": "NVIDIA GeForce 256"},
        {"gpu_name": "NVIDIA GeForce 2 MX"},
        {"gpu_name": "NVIDIA GeForce 2 GTS"},
        {"gpu_name": "NVIDIA GeForce 3"},
        {"gpu_name": "NVIDIA GeForce 4 MX"},
        {"gpu_name": "NVIDIA GeForce 4 Ti"},
        {"gpu_name": "NVIDIA GeForce FX 5200"},
        {"gpu_name": "NVIDIA GeForce FX 5800"},
        {"gpu_name": "NVIDIA GeForce 6200"},
        {"gpu_name": "NVIDIA GeForce 6600"},
        {"gpu_name": "NVIDIA GeForce 6800"},
        {"gpu_name": "NVIDIA GeForce 7300"},
        {"gpu_name": "NVIDIA GeForce 7600"},
        {"gpu_name": "NVIDIA GeForce 7800 GTX"},
        {"gpu_name": "NVIDIA GeForce 7900 GTX"},
        {"gpu_name": "NVIDIA GeForce 8800 GTX"},
        {"gpu_name": "NVIDIA GeForce 8800 Ultra"},
        {"gpu_name": "NVIDIA GeForce 9600 GT"},
        {"gpu_name": "NVIDIA GeForce 9800 GTX"},
        {"gpu_name": "NVIDIA GeForce GTX 260"},
        {"gpu_name": "NVIDIA GeForce GTX 280"},
        {"gpu_name": "NVIDIA GeForce GTX 460"},
        {"gpu_name": "NVIDIA GeForce GTX 560"},
        {"gpu_name": "NVIDIA GeForce GTX 580"},
        {"gpu_name": "NVIDIA GeForce GTX 680"},
        {"gpu_name": "NVIDIA GeForce GTX 780"},
        {"gpu_name": "NVIDIA GeForce GTX 980"},
        {"gpu_name": "NVIDIA GeForce GTX 1080"},
        {"gpu_name": "NVIDIA GeForce GTX 1080 Ti"},
        {"gpu_name": "NVIDIA GeForce RTX 2060"},
        {"gpu_name": "NVIDIA GeForce RTX 2070"},
        {"gpu_name": "NVIDIA GeForce RTX 2080"},
        {"gpu_name": "NVIDIA GeForce RTX 2080 Ti"},
        {"gpu_name": "NVIDIA GeForce RTX 3060"},
        {"gpu_name": "NVIDIA GeForce RTX 3060 Ti"},
        {"gpu_name": "NVIDIA GeForce RTX 3070"},
        {"gpu_name": "NVIDIA GeForce RTX 3080"},
        {"gpu_name": "NVIDIA GeForce RTX 3090"},
        {"gpu_name": "NVIDIA GeForce RTX 4060"},
        {"gpu_name": "NVIDIA GeForce RTX 4070"},
        {"gpu_name": "NVIDIA GeForce RTX 4070 Ti"},
        {"gpu_name": "NVIDIA GeForce RTX 4080"},
        {"gpu_name": "NVIDIA GeForce RTX 4090"},
        {"gpu_name": "NVIDIA GeForce RTX 5060"},
        {"gpu_name": "NVIDIA GeForce RTX 5060 Ti"},
        {"gpu_name": "NVIDIA GeForce RTX 5070"},
        {"gpu_name": "NVIDIA GeForce RTX 5070 Ti"},
        {"gpu_name": "NVIDIA GeForce RTX 5080"},
        {"gpu_name": "NVIDIA GeForce RTX 5090"},
        {"gpu_name": "NVIDIA Quadro K600"},
        {"gpu_name": "NVIDIA Quadro K4000"},
        {"gpu_name": "NVIDIA Quadro P2000"},
        {"gpu_name": "NVIDIA Quadro RTX 4000"},
        {"gpu_name": "NVIDIA Quadro RTX 6000"},
        {"gpu_name": "NVIDIA Quadro RTX A6000"},
        {"gpu_name": "NVIDIA Tesla C1060"},
        {"gpu_name": "NVIDIA Tesla K20"},
        {"gpu_name": "NVIDIA Tesla K40"},
        {"gpu_name": "NVIDIA Tesla V100"},
        {"gpu_name": "NVIDIA A100"},
        {"gpu_name": "NVIDIA A40"},
        {"gpu_name": "NVIDIA A800"},
        {"gpu_name": "NVIDIA H100"},
        {"gpu_name": "NVIDIA H200"},
        {"gpu_name": "NVIDIA L40"},
        {"gpu_name": "AMD Radeon 7000"},
        {"gpu_name": "AMD Radeon 8500"},
        {"gpu_name": "AMD Radeon 9700 Pro"},
        {"gpu_name": "AMD Radeon 9800 Pro"},
        {"gpu_name": "AMD Radeon X800"},
        {"gpu_name": "AMD Radeon X1800"},
        {"gpu_name": "AMD Radeon HD 2900 XT"},
        {"gpu_name": "AMD Radeon HD 3870"},
        {"gpu_name": "AMD Radeon HD 4870"},
        {"gpu_name": "AMD Radeon HD 5870"},
        {"gpu_name": "AMD Radeon HD 6970"},
        {"gpu_name": "AMD Radeon HD 7970"},
        {"gpu_name": "AMD Radeon R9 290X"},
        {"gpu_name": "AMD Radeon R9 390X"},
        {"gpu_name": "AMD Radeon RX 480"},
        {"gpu_name": "AMD Radeon RX 580"},
        {"gpu_name": "AMD Radeon RX Vega 56"},
        {"gpu_name": "AMD Radeon RX Vega 64"},
        {"gpu_name": "AMD Radeon RX 5700"},
        {"gpu_name": "AMD Radeon RX 5700 XT"},
        {"gpu_name": "AMD Radeon RX 6700 XT"},
        {"gpu_name": "AMD Radeon RX 6800"},
        {"gpu_name": "AMD Radeon RX 6800 XT"},
        {"gpu_name": "AMD Radeon RX 6900 XT"},
        {"gpu_name": "AMD Radeon RX 7600"},
        {"gpu_name": "AMD Radeon RX 7700 XT"},
        {"gpu_name": "AMD Radeon RX 7800 XT"},
        {"gpu_name": "AMD Radeon RX 7900 XT"},
        {"gpu_name": "AMD Radeon RX 7900 XTX"},
        {"gpu_name": "AMD Radeon RX 9060 XT"},
        {"gpu_name": "AMD FirePro W7000"},
        {"gpu_name": "AMD FirePro W9100"},
        {"gpu_name": "AMD Radeon Pro WX 7100"},
        {"gpu_name": "AMD Radeon Pro WX 8200"},
        {"gpu_name": "AMD Radeon Pro W5700"},
        {"gpu_name": "AMD Radeon Pro W6800"},
        {"gpu_name": "AMD Instinct MI25"},
        {"gpu_name": "AMD Instinct MI50"},
        {"gpu_name": "AMD Instinct MI100"},
        {"gpu_name": "AMD Instinct MI200"},
        {"gpu_name": "AMD Instinct MI250"},
        {"gpu_name": "AMD Instinct MI300X"},
        {"gpu_name": "AMD Instinct MI300A"},
        {"gpu_name": "Intel HD Graphics 2000"},
        {"gpu_name": "Intel HD Graphics 3000"},
        {"gpu_name": "Intel HD Graphics 4000"},
        {"gpu_name": "Intel HD Graphics 530"},
        {"gpu_name": "Intel UHD Graphics 620"},
        {"gpu_name": "Intel UHD Graphics 630"},
        {"gpu_name": "Intel Iris Plus Graphics"},
        {"gpu_name": "Intel Iris Xe Graphics"},
        {"gpu_name": "Intel Arc A380"},
        {"gpu_name": "Intel Arc A580"},
        {"gpu_name": "Intel Arc A750"},
        {"gpu_name": "Intel Arc A770"},
        {"gpu_name": "Intel Arc B570"},
        {"gpu_name": "Intel Arc B580"},
        {"gpu_name": "Intel Data Center GPU Flex 140"},
        {"gpu_name": "Intel Data Center GPU Flex 170"},
        {"gpu_name": "Intel Data Center GPU Max 1100"},
        {"gpu_name": "Intel Data Center GPU Max 1550"},
        {"gpu_name": "ATI Rage 128"},
        {"gpu_name": "ATI Rage Pro"},
        {"gpu_name": "ATI Radeon 7500"},
        {"gpu_name": "S3 Savage 2000"},
        {"gpu_name": "S3 ViRGE"},
        {"gpu_name": "Matrox Millennium"},
        {"gpu_name": "Matrox Mystique"},
        {"gpu_name": "Matrox G200"},
        {"gpu_name": "Matrox G400"},
        {"gpu_name": "PowerVR Kyro"},
        {"gpu_name": "PowerVR Kyro II"},
        {"gpu_name": "VIA S3 DeltaChrome"},
        {"gpu_name": "VIA S3 Chrome"},
        {"gpu_name": "ARM Mali-400"},
        {"gpu_name": "ARM Mali-T604"},
        {"gpu_name": "ARM Mali-T760"},
        {"gpu_name": "ARM Mali-G71"},
        {"gpu_name": "ARM Mali-G76"},
        {"gpu_name": "ARM Mali-G77"},
        {"gpu_name": "ARM Mali-G78"},
        {"gpu_name": "Qualcomm Adreno 320"},
        {"gpu_name": "Qualcomm Adreno 420"},
        {"gpu_name": "Qualcomm Adreno 530"},
        {"gpu_name": "Qualcomm Adreno 630"},
        {"gpu_name": "Qualcomm Adreno 730"},
        {"gpu_name": "Qualcomm Adreno 750"},
        {"gpu_name": "Imagination PowerVR SGX535"},
        {"gpu_name": "Imagination PowerVR SGX543"},
        {"gpu_name": "Imagination PowerVR G6200"},
        {"gpu_name": "Imagination PowerVR G6430"},
        {"gpu_name": "Apple GPU A7"},
        {"gpu_name": "Apple GPU A8"},
        {"gpu_name": "Apple GPU A9"},
        {"gpu_name": "Apple GPU A10"},
        {"gpu_name": "Apple GPU A11"},
        {"gpu_name": "Apple GPU A12"},
        {"gpu_name": "Apple GPU A13"},
        {"gpu_name": "Apple GPU A14"},
        {"gpu_name": "Apple GPU A15"},
        {"gpu_name": "Apple GPU A16"},
        {"gpu_name": "Apple GPU A17 Pro"},
        {"gpu_name": "Apple GPU M1"},
        {"gpu_name": "Apple GPU M2"},
        {"gpu_name": "Apple GPU M3"},
        {"gpu_name": "Apple GPU M4"},
        {"gpu_name": "Broadcom VideoCore IV"},
        {"gpu_name": "Broadcom VideoCore VI"},
        {"gpu_name": "Vivante GC1000"},
        {"gpu_name": "Vivante GC2000"},
        {"gpu_name": "Vivante GC7000"},
    ]
    
    with Session(engine) as session:
        # Check if GPU types already exist to avoid duplicates
        existing_gputypes = session.exec(select(GPUType)).all()
        existing_gpu_names = {gpu.gpu_name for gpu in existing_gputypes}
        
        gputypes_to_add = []
        for gpu_data in gputypes_data:
            if gpu_data["gpu_name"] not in existing_gpu_names:
                gputypes_to_add.append(GPUType(**gpu_data))
        
        if gputypes_to_add:
            session.add_all(gputypes_to_add)
            session.commit()
            print(f"Added {len(gputypes_to_add)} GPU types to the database.")
        else:
            print("All GPU types already exist in the database.")

if __name__ == "__main__":
    seed_gputypes()