"""empty message

Revision ID: 0afbde89b859
Revises: 6dd1361485da
Create Date: 2025-07-21 17:19:27.769444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '0afbde89b859'
down_revision: Union[str, Sequence[str], None] = '6dd1361485da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('virtualmachine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ram_mb', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('disk_size_mb', sa.Integer(), nullable=True))
        batch_op.drop_column('ram_gb')
        batch_op.drop_column('disk_size_gb')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('virtualmachine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disk_size_gb', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ram_gb', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('disk_size_mb')
        batch_op.drop_column('ram_mb')

    # ### end Alembic commands ###
