"""empty message

Revision ID: 175d8d094258
Revises: 9a66155bfe77
Create Date: 2025-07-17 16:37:03.876299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '175d8d094258'
down_revision: Union[str, Sequence[str], None] = '9a66155bfe77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appuser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('priv_level_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'department', ['department_id'], ['dept_id'])
        batch_op.create_foreign_key(None, 'privilegelevel', ['priv_level_id'], ['priv_id'])
        batch_op.drop_column('priv_level')
        batch_op.drop_column('department')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appuser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('priv_level', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('priv_level_id')
        batch_op.drop_column('department_id')

    # ### end Alembic commands ###
