"""empty message

Revision ID: 1cf8cc30016f
Revises: 2fc7bef620c8
Create Date: 2025-07-18 10:31:48.028030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1cf8cc30016f'
down_revision: Union[str, Sequence[str], None] = '2fc7bef620c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('osversion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('osedition_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'osedition', ['osedition_id'], ['osedition_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('osversion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('osedition_id')

    # ### end Alembic commands ###
