"""empty message

Revision ID: 1efb555b288d
Revises: 68f71e0fdbc7
Create Date: 2025-07-20 18:17:19.458786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1efb555b288d'
down_revision: Union[str, Sequence[str], None] = '68f71e0fdbc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('virtualizationsource',
    sa.Column('virtsource_id', sa.Integer(), nullable=False),
    sa.Column('virt_source', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('virtsource_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('virtualizationsource')
    # ### end Alembic commands ###
