"""empty message

Revision ID: 202e7f8f0426
Revises: 1cf8cc30016f
Create Date: 2025-07-18 12:33:45.177652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '202e7f8f0426'
down_revision: Union[str, Sequence[str], None] = '1cf8cc30016f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hardwaremanufacturer', schema=None) as batch_op:
        batch_op.drop_column('hwmanu_rep')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hardwaremanufacturer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hwmanu_rep', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
