"""empty message

Revision ID: 26ad63a5d92b
Revises: 7e5565f42332
Create Date: 2025-07-18 14:29:05.156852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '26ad63a5d92b'
down_revision: Union[str, Sequence[str], None] = '7e5565f42332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gputype',
    sa.Column('gpu_id', sa.Integer(), nullable=False),
    sa.Column('gpu_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('gpu_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gputype')
    # ### end Alembic commands ###
