"""empty message

Revision ID: 2fc7bef620c8
Revises: 5a74224a5cff
Create Date: 2025-07-18 10:31:17.542981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '2fc7bef620c8'
down_revision: Union[str, Sequence[str], None] = '5a74224a5cff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('osedition',
    sa.Column('osedition_id', sa.Integer(), nullable=False),
    sa.Column('osedition_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('osedition_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('osedition')
    # ### end Alembic commands ###
