"""empty message

Revision ID: 4f0b141e6885
Revises: 12adaffe3ffe
Create Date: 2025-07-18 20:10:53.642832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4f0b141e6885'
down_revision: Union[str, Sequence[str], None] = '12adaffe3ffe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('asset_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('serial_no', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('letterkenny_barcode', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('systype_id', sa.Integer(), nullable=False),
    sa.Column('hwmanu_id', sa.Integer(), nullable=True),
    sa.Column('os_id', sa.Integer(), nullable=True),
    sa.Column('osedition_id', sa.Integer(), nullable=True),
    sa.Column('osversion_id', sa.Integer(), nullable=True),
    sa.Column('physical_memory', sa.Integer(), nullable=True),
    sa.Column('physical_storage_total', sa.Integer(), nullable=True),
    sa.Column('physical_storage_used', sa.Integer(), nullable=True),
    sa.Column('physical_storage_remaining', sa.Integer(), nullable=True),
    sa.Column('av_deployment', sa.Boolean(), nullable=False),
    sa.Column('cpu_id', sa.Integer(), nullable=True),
    sa.Column('gpu_id', sa.Integer(), nullable=True),
    sa.Column('last_acas_scan', sa.DateTime(), nullable=True),
    sa.Column('last_scap_scan', sa.DateTime(), nullable=True),
    sa.Column('last_log_collection', sa.DateTime(), nullable=True),
    sa.Column('last_image_collection', sa.DateTime(), nullable=True),
    sa.Column('last_datfile_update', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['building.building_id'], ),
    sa.ForeignKeyConstraint(['cpu_id'], ['cputype.cpu_id'], ),
    sa.ForeignKeyConstraint(['floor_id'], ['floor.floor_id'], ),
    sa.ForeignKeyConstraint(['gpu_id'], ['gputype.gpu_id'], ),
    sa.ForeignKeyConstraint(['hwmanu_id'], ['hardwaremanufacturer.hwmanu_id'], ),
    sa.ForeignKeyConstraint(['os_id'], ['operatingsystem.os_id'], ),
    sa.ForeignKeyConstraint(['osedition_id'], ['osedition.osedition_id'], ),
    sa.ForeignKeyConstraint(['osversion_id'], ['osversion.osversion_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], ),
    sa.ForeignKeyConstraint(['systype_id'], ['systype.systype_id'], ),
    sa.PrimaryKeyConstraint('asset_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset')
    # ### end Alembic commands ###
