"""empty message

Revision ID: 5701ff8938d0
Revises: cf5ce5d79c6b
Create Date: 2025-07-23 23:54:40.439068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5701ff8938d0'
down_revision: Union[str, Sequence[str], None] = 'cf5ce5d79c6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('softwarecatalog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compliance_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
        batch_op.add_column(sa.Column('army_gold_master', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('softwarecatalog', schema=None) as batch_op:
        batch_op.drop_column('army_gold_master')
        batch_op.drop_column('compliance_status')

    # ### end Alembic commands ###
