"""empty message

Revision ID: 5a74224a5cff
Revises: 725402cff88f
Create Date: 2025-07-18 10:30:31.278421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5a74224a5cff'
down_revision: Union[str, Sequence[str], None] = '725402cff88f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('osversion',
    sa.Column('osversion_id', sa.Integer(), nullable=False),
    sa.Column('os_id', sa.Integer(), nullable=False),
    sa.Column('osversion_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.ForeignKeyConstraint(['os_id'], ['operatingsystem.os_id'], ),
    sa.PrimaryKeyConstraint('osversion_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('osversion')
    # ### end Alembic commands ###
