"""empty message

Revision ID: 629e58100a98
Revises: 76cb6feacac5
Create Date: 2025-07-18 10:24:02.718471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '629e58100a98'
down_revision: Union[str, Sequence[str], None] = '76cb6feacac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('floor',
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('floor_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('floor_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('floor')
    # ### end Alembic commands ###
