"""empty message

Revision ID: 68f71e0fdbc7
Revises: 0efa150e1d21
Create Date: 2025-07-20 18:10:21.410268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '68f71e0fdbc7'
down_revision: Union[str, Sequence[str], None] = '0efa150e1d21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vmtype',
    sa.Column('vmtype_id', sa.Integer(), nullable=False),
    sa.Column('vm_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('vmtype_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vmtype')
    # ### end Alembic commands ###
