"""empty message

Revision ID: 6dd1361485da
Revises: 78d3cde3ee50
Create Date: 2025-07-20 18:30:37.340837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6dd1361485da'
down_revision: Union[str, Sequence[str], None] = '78d3cde3ee50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('virtualmachine',
    sa.Column('virtmachine_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('imgcollection_id', sa.Integer(), nullable=False),
    sa.Column('virtsource_id', sa.Integer(), nullable=False),
    sa.Column('creator_employee_id', sa.Integer(), nullable=False),
    sa.Column('vmtype_id', sa.Integer(), nullable=False),
    sa.Column('vmstatus_id', sa.Integer(), nullable=False),
    sa.Column('ram_gb', sa.Integer(), nullable=True),
    sa.Column('cpu_cores', sa.Integer(), nullable=True),
    sa.Column('disk_size_gb', sa.Integer(), nullable=True),
    sa.Column('acas_scan_completed', sa.Boolean(), nullable=False),
    sa.Column('scap_scan_completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.asset_id'], ),
    sa.ForeignKeyConstraint(['creator_employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['imgcollection_id'], ['imagecollection.imgcollection_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
    sa.ForeignKeyConstraint(['virtsource_id'], ['virtualizationsource.virtsource_id'], ),
    sa.ForeignKeyConstraint(['vmstatus_id'], ['vmstatus.vmstatus_id'], ),
    sa.ForeignKeyConstraint(['vmtype_id'], ['vmtype.vmtype_id'], ),
    sa.PrimaryKeyConstraint('virtmachine_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('virtualmachine')
    # ### end Alembic commands ###
