"""empty message

Revision ID: 702de732ebe0
Revises: 0afbde89b859
Create Date: 2025-07-21 18:06:47.132283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '702de732ebe0'
down_revision: Union[str, Sequence[str], None] = '0afbde89b859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('useractivity',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('activity_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('activity_description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('related_asset_id', sa.Integer(), nullable=True),
    sa.Column('related_project_id', sa.Integer(), nullable=True),
    sa.Column('related_vm_id', sa.Integer(), nullable=True),
    sa.Column('related_image_id', sa.Integer(), nullable=True),
    sa.Column('related_log_id', sa.Integer(), nullable=True),
    sa.Column('related_dat_id', sa.Integer(), nullable=True),
    sa.Column('activity_timestamp', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('activity_metadata', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['related_asset_id'], ['asset.asset_id'], ),
    sa.ForeignKeyConstraint(['related_dat_id'], ['datupdate.datupdate_id'], ),
    sa.ForeignKeyConstraint(['related_image_id'], ['imagecollection.imgcollection_id'], ),
    sa.ForeignKeyConstraint(['related_log_id'], ['logcollection.logcollection_id'], ),
    sa.ForeignKeyConstraint(['related_project_id'], ['project.project_id'], ),
    sa.ForeignKeyConstraint(['related_vm_id'], ['virtualmachine.virtmachine_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['appuser.id'], ),
    sa.PrimaryKeyConstraint('activity_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('useractivity')
    # ### end Alembic commands ###
