"""empty message

Revision ID: 725402cff88f
Revises: a1e4990eba65
Create Date: 2025-07-18 10:29:39.295550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '725402cff88f'
down_revision: Union[str, Sequence[str], None] = 'a1e4990eba65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operatingsystem',
    sa.Column('os_id', sa.Integer(), nullable=False),
    sa.Column('os_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('os_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operatingsystem')
    # ### end Alembic commands ###
