"""empty message

Revision ID: 7307306ba3b7
Revises: b3c4d5e6f7a8
Create Date: 2025-07-17 16:24:27.848269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7307306ba3b7'
down_revision: Union[str, Sequence[str], None] = 'b3c4d5e6f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('privilegelevel',
    sa.Column('priv_id', sa.Integer(), nullable=False),
    sa.Column('priv_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('priv_description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('priv_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('privilegelevel')
    # ### end Alembic commands ###
