"""empty message

Revision ID: 78d3cde3ee50
Revises: 1efb555b288d
Create Date: 2025-07-20 18:27:15.161626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '78d3cde3ee50'
down_revision: Union[str, Sequence[str], None] = '1efb555b288d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vmstatus',
    sa.Column('vmstatus_id', sa.Integer(), nullable=False),
    sa.Column('vm_status', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.PrimaryKeyConstraint('vmstatus_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vmstatus')
    # ### end Alembic commands ###
