"""empty message

Revision ID: 799437cf0442
Revises: c4cf40f0e25d
Create Date: 2025-07-18 13:57:15.888165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '799437cf0442'
down_revision: Union[str, Sequence[str], None] = 'c4cf40f0e25d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logtype',
    sa.Column('logtype_id', sa.Integer(), nullable=False),
    sa.Column('logtype', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('logtype_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logtype')
    # ### end Alembic commands ###
