"""empty message

Revision ID: 7dab3acf306a
Revises: 202e7f8f0426
Create Date: 2025-07-18 12:36:00.267301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7dab3acf306a'
down_revision: Union[str, Sequence[str], None] = '202e7f8f0426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hardwaremanufacturer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hardwaremanufacturer', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
