"""empty message

Revision ID: 7e5565f42332
Revises: 3f5ba5c9da7f
Create Date: 2025-07-18 14:27:22.250309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7e5565f42332'
down_revision: Union[str, Sequence[str], None] = '3f5ba5c9da7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cputype',
    sa.Column('cpu_id', sa.Integer(), nullable=False),
    sa.Column('cpu_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('cpu_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cputype')
    # ### end Alembic commands ###
