"""empty message

Revision ID: 93b841d2894d
Revises: f2ef0ce43a5f
Create Date: 2025-07-20 13:19:14.244420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '93b841d2894d'
down_revision: Union[str, Sequence[str], None] = 'f2ef0ce43a5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imagecollection',
    sa.Column('imgcollection_id', sa.Integer(), nullable=False),
    sa.Column('imgcollection_date', sa.DateTime(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('img_size_mb', sa.Float(), nullable=True),
    sa.Column('imgmethod_id', sa.Integer(), nullable=False),
    sa.Column('imaging_result', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('imaging_comments', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.asset_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['imgmethod_id'], ['imagingmethod.imgmethod_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
    sa.PrimaryKeyConstraint('imgcollection_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imagecollection')
    # ### end Alembic commands ###
