"""empty message

Revision ID: 9470ece7683a
Revises: c82cd688cbcb
Create Date: 2025-07-18 16:20:00.610914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9470ece7683a'
down_revision: Union[str, Sequence[str], None] = 'c82cd688cbcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('floor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('building_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'building', ['building_id'], ['building_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('floor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('building_id')

    # ### end Alembic commands ###
