"""empty message

Revision ID: 9a66155bfe77
Revises: 7307306ba3b7
Create Date: 2025-07-17 16:29:53.761419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9a66155bfe77'
down_revision: Union[str, Sequence[str], None] = '7307306ba3b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.Column('dept_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('dept_description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('dept_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
