"""empty message

Revision ID: 9eaeabbc6461
Revises: b2fa26041a2b
Create Date: 2025-07-17 15:30:51.330994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9eaeabbc6461'
down_revision: Union[str, Sequence[str], None] = 'b2fa26041a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('swmanufacturer',
    sa.Column('swmanu_id', sa.Integer(), nullable=False),
    sa.Column('swmanu_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('swmanu_rep', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('swmanu_contact', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('weblink', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('swmanu_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('swmanufacturer')
    # ### end Alembic commands ###
