"""empty message

Revision ID: a1e4990eba65
Revises: 04fec3e519f4
Create Date: 2025-07-18 10:28:47.384905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a1e4990eba65'
down_revision: Union[str, Sequence[str], None] = '04fec3e519f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('systype',
    sa.Column('systype_id', sa.Integer(), nullable=False),
    sa.Column('systype_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('systype_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('systype')
    # ### end Alembic commands ###
