"""empty message

Revision ID: b2fa26041a2b
Revises: fe6fb4022898
Create Date: 2025-07-17 15:26:09.764892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b2fa26041a2b'
down_revision: Union[str, Sequence[str], None] = 'fe6fb4022898'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hardwaremanufacturer',
    sa.Column('hwmanu_id', sa.Integer(), nullable=False),
    sa.Column('hwmanu_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('hwmanu_rep', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('hwmanu_contact', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('weblink', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('hwmanu_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hardwaremanufacturer')
    # ### end Alembic commands ###
