"""empty message

Revision ID: bb427c7ef7da
Revises: 799437cf0442
Create Date: 2025-07-18 14:09:11.077786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'bb427c7ef7da'
down_revision: Union[str, Sequence[str], None] = '799437cf0442'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imagingmethod',
    sa.Column('imgmethod_id', sa.Integer(), nullable=False),
    sa.Column('img_method', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('imgmethod_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imagingmethod')
    # ### end Alembic commands ###
