"""empty message

Revision ID: c4cf40f0e25d
Revises: 7dab3acf306a
Create Date: 2025-07-18 12:55:08.715898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c4cf40f0e25d'
down_revision: Union[str, Sequence[str], None] = '7dab3acf306a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swmanufacturer', schema=None) as batch_op:
        batch_op.drop_column('swmanu_rep')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swmanufacturer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('swmanu_rep', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
