"""empty message

Revision ID: cf5ce5d79c6b
Revises: 00faf5453aaa
Create Date: 2025-07-23 18:46:50.952306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'cf5ce5d79c6b'
down_revision: Union[str, Sequence[str], None] = '00faf5453aaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('softwarecatalog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sw_architecture_compatibility', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
        batch_op.add_column(sa.Column('dod_compliant', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('softwarecatalog', schema=None) as batch_op:
        batch_op.drop_column('dod_compliant')
        batch_op.drop_column('sw_architecture_compatibility')

    # ### end Alembic commands ###
