"""empty message

Revision ID: d85d687a1046
Revises: ffb6e590862e
Create Date: 2025-07-25 18:42:13.768736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd85d687a1046'
down_revision: Union[str, Sequence[str], None] = 'ffb6e590862e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_directory',
    sa.Column('directory_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('full_path', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('directory_type', sa.Enum('SYSTEM', 'USER', name='directorytype'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_system_directory', sa.Boolean(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('can_create_subdirs', sa.Boolean(), nullable=False),
    sa.Column('can_upload_files', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.dept_id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['file_directory.directory_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
    sa.PrimaryKeyConstraint('directory_id')
    )
    with op.batch_alter_table('file_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('directory_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'file_directory', ['directory_id'], ['directory_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_metadata', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('directory_id')

    op.drop_table('file_directory')
    # ### end Alembic commands ###
