"""empty message

Revision ID: f2ef0ce43a5f
Revises: 4f0b141e6885
Create Date: 2025-07-19 21:42:27.766624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f2ef0ce43a5f'
down_revision: Union[str, Sequence[str], None] = '4f0b141e6885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logcollection',
    sa.Column('logcollection_id', sa.Integer(), nullable=False),
    sa.Column('logcollection_date', sa.DateTime(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('logtype_id', sa.Integer(), nullable=False),
    sa.Column('logcollection_result', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('logcollection_comments', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.asset_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['logtype_id'], ['logtype.logtype_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
    sa.PrimaryKeyConstraint('logcollection_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logcollection')
    # ### end Alembic commands ###
